-- Disable RLS on all tables (service role key is only used server-side)
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE proposals DISABLE ROW LEVEL SECURITY;
ALTER TABLE votes DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE league_settings DISABLE ROW LEVEL SECURITY;
